---
- hosts: webserver
  tasks:
    - name: Delete index.html file
      file:
         path: /var/www/html/index.html
         state: absent

    - name: Stop httpd service
      service:
        name: httpd
        state: stopped

    - name: Remove httpd service
      yum:
        name: httpd
        state: removed

...

