---
- hosts: webserver
  
  tasks:
    - name: Update tomcat-usr.xml file
      replace:
        path: /usr/share/tomcat/conf/tomcat-users.xml
        regexp: '^<!-- <user name="admin" password="adminadmin" roles="admin,manager,admin-gui,admin-script,manager-gui,manager-script,manager-jmx,manager-status" /> -->'
        replace: '<user name="admin" password="adminadmin" roles="admin,manager,admin-gui,admin-script,manager-gui,manager-script,manager-jmx,manager-status" />'
      
    #Restart the service#
    - name: Restart tomcat service
      service:
        name: tomcat
        state: restarted
...
